AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  party-backend

  Backend for party invite webapp. Lambda functions behind API Gateway.

Globals:
  Function:
    Timeout: 3

Resources:
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index/
      Handler: index.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          CORS_ORIGIN: "https://party.matthewjamesquinn.com"
      Events:
        PartyAPI:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref PartyApi

  InviteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: invite/
      Handler: invite.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: "guests"
          CORS_ORIGIN: "https://party.matthewjamesquinn.com"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/guests
      Events:
        PartyAPI:
          Type: Api
          Properties:
            Path: /invite/{uuid}
            Method: get
            RestApiId: !Ref PartyApi
            RequestParameters:
              - method.request.path.uuid

  UpdateGuestRSVPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_guest_rsvp/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: "guests"
          CORS_ORIGIN: "https://party.matthewjamesquinn.com"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/guests
      Events:
        PartyAPI:
          Type: Api
          Properties:
            Path: /rsvp
            Method: post
            RestApiId: !Ref PartyApi

  PartyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: party-api
      StageName: Prod
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://party.matthewjamesquinn.com'"
