version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install ansible
      - export HOST_IP=$(aws ssm get-parameter --name "/partyApp/Ansible/host-ip" --with-decryption --query 'Parameter.Value' --output text)
      - export GIT_REPO=$(aws ssm get-parameter --name "/partyApp/Ansible/git-repo" --with-decryption --query 'Parameter.Value' --output text)
      - export API_URL=$(aws ssm get-parameter --name "/partyApp/sam/api-url" --with-decryption --query 'Parameter.Value' --output text)
      - sed -i "s|__HOST_IP__|$HOST_IP|g" infra/inventory/hosts.ini
      - sed -i "s|__GIT_REPO__|$GIT_REPO|g" infra/playbook.yml
      - sed -i "s|__API_URL__|$API_URL|g" infra/playbook.yml
      - aws ssm get-parameter --name "/partyApp/Ansible/ssh-key" --with-decryption --query "Parameter.Value" --output text > ec2_key.pem
      - chmod 600 ec2_key.pem
  build:
    commands:
      - ansible-playbook infra/playbook.yml -i infra/inventory/hosts.ini
