- name: Deploy Flask Web App
  hosts: web
  become: true

  vars:
    project_dir: /home/ec2-user/birthday-party-website

    git_repo: __GIT_REPO__

    api_url: __API_URL__

  roles:
  - webapp
  - nginx