- name: Install Python and dependencies
  yum:
    name:
      - python3
      - git
    state: present

- name: Clone Flask app repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_dir }}"
    version: serverless

- name: Copy .env file to remote server
  copy:
    src: ../.env
    dest: "{{ project_dir }}/.env"
    owner: ec2-user
    group: webapp
    mode: '0644'

- name: Inject API url to HTML files
  ansible.builtin.template:
    src: /website/invite.html.j2
    dest: /src/templates/invite.html
    mode: '0644'

- name: Create virtual environment
  command: python3 -m venv {{ project_dir }}/venv
  args:
    creates: "{{ project_dir }}/venv"

- name: Install requirements
  pip:
    requirements: "{{ project_dir }}/requirements.txt"
    virtualenv: "{{ project_dir }}/venv"

- name: Copy Gunicorn systemd service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    mode: '0644'

- name: Start and enable Gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    state: restarted
    daemon_reload: yes
