- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Copy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Start and enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
